### ISSUE TITLE
Support multiple embeddings for query

### ISSUE THREAD

**Issue by Konard** [deep-foundation/russian-laws-bot#6]
Example:
https://github.com/RGU-Computing/clood/blob/1143687e117a7d596f73678a975d2931e645a56e/api/cbrcycle/retrieve.py#L447-L477

**Comment by FreePhoenix888** [comment]
How to do it?

**Comment by Konard** [comment]
@FreePhoenix888 this task is on me now. To do it I will use example and I will integrate it into current code, and this will improve the search performance.
